server:
  port: 8083

spring:
  application:
    name: load-test


  datasource:
    url: jdbc:postgresql://localhost:5434/load_test_db
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true